version: '3'

services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
  app2:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
