name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, ready_for_review, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Build Docker image
        run: docker info
      -
        name: Build Docker image
        run: docker compose build
